
// This file has been generated by the GUI designer. Do not modify.

public partial class frmMain
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action dialogInfoAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menuBar;
	private global::Gtk.ProgressBar progBar;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label lblDeletionInst;
	private global::Gtk.VBox vbox6;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.VBox vbox7;
	private global::Gtk.CheckButton chkTrash;
	private global::Gtk.CheckButton chkThumbnails;
	private global::Gtk.CheckButton chkMru;
	private global::Gtk.CheckButton chkBashHist;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label lblDelMethodInst;
	private global::Gtk.RadioButton rdoMinimalShred;
	private global::Gtk.RadioButton rdoStandardShred;
	private global::Gtk.RadioButton rdoExtremeShred;
	private global::Gtk.Button btnDelete;
	private global::Gtk.Label lblShred;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox10;
	private global::Gtk.Label lblUpdateInst;
	private global::Gtk.VBox vbox11;
	private global::Gtk.Button btnRefreshPackageCatalog;
	private global::Gtk.Button btnInstallUpdates;
	private global::Gtk.Label lblSystemUpdate;
	private global::Gtk.HBox hbox4;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label lblFirewallInst;
	private global::Gtk.Button btnActivateFirewall;
	private global::Gtk.Button btnDeavtivateFirewall;
	private global::Gtk.Label lblFirewall;
	private global::Gtk.HBox hbox5;
	private global::Gtk.VBox vbox4;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Label lblAvInst;
	private global::Gtk.RadioButton rdoClamavHomeFolder;
	private global::Gtk.RadioButton rdoClamavExternal;
	private global::Gtk.RadioButton rdoClamavFull;
	private global::Gtk.Button btnVirusScan;
	private global::Gtk.Button btnFreshclam;
	private global::Gtk.Label lblAntivirus;
	private global::Gtk.Frame fraOutput;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtOutput;
	private global::Gtk.Label lblOutput;
	private global::Gtk.HBox hbox3;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.Button btnClear;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget frmMain
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
		w1.Add (this.dialogInfoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "frmMain";
		this.Title = global::Mono.Unix.Catalog.GetString ("Linux Security Center (Linux Mint)");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.DefaultWidth = 620;
		this.DefaultHeight = 420;
		// Container child frmMain.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menuBar'><menu name='HelpAction' action='HelpAction'><menuitem name='dialogInfoAction' action='dialogInfoAction'/></menu></menubar></ui>");
		this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuBar")));
		this.menuBar.Name = "menuBar";
		this.menuBar.PackDirection = ((global::Gtk.PackDirection)(1));
		this.vbox1.Add (this.menuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.progBar = new global::Gtk.ProgressBar ();
		this.progBar.Name = "progBar";
		this.vbox1.Add (this.progBar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.progBar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lblDeletionInst = new global::Gtk.Label ();
		this.lblDeletionInst.Name = "lblDeletionInst";
		this.lblDeletionInst.Ypad = 5;
		this.lblDeletionInst.LabelProp = global::Mono.Unix.Catalog.GetString ("Select items to <b>shred</b> below:");
		this.lblDeletionInst.UseMarkup = true;
		this.lblDeletionInst.Wrap = true;
		this.lblDeletionInst.Justify = ((global::Gtk.Justification)(2));
		this.vbox5.Add (this.lblDeletionInst);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblDeletionInst]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
		w5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.chkTrash = new global::Gtk.CheckButton ();
		this.chkTrash.CanFocus = true;
		this.chkTrash.Name = "chkTrash";
		this.chkTrash.Label = global::Mono.Unix.Catalog.GetString ("Trash / _Wastebasket");
		this.chkTrash.DrawIndicator = true;
		this.chkTrash.UseUnderline = true;
		this.vbox7.Add (this.chkTrash);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.chkTrash]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.chkThumbnails = new global::Gtk.CheckButton ();
		this.chkThumbnails.CanFocus = true;
		this.chkThumbnails.Name = "chkThumbnails";
		this.chkThumbnails.Label = global::Mono.Unix.Catalog.GetString ("_Image Cache");
		this.chkThumbnails.DrawIndicator = true;
		this.chkThumbnails.UseUnderline = true;
		this.vbox7.Add (this.chkThumbnails);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.chkThumbnails]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.chkMru = new global::Gtk.CheckButton ();
		this.chkMru.CanFocus = true;
		this.chkMru.Name = "chkMru";
		this.chkMru.Label = global::Mono.Unix.Catalog.GetString ("_Most Recently Used List");
		this.chkMru.DrawIndicator = true;
		this.chkMru.UseUnderline = true;
		this.vbox7.Add (this.chkMru);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.chkMru]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.chkBashHist = new global::Gtk.CheckButton ();
		this.chkBashHist.CanFocus = true;
		this.chkBashHist.Name = "chkBashHist";
		this.chkBashHist.Label = global::Mono.Unix.Catalog.GetString ("Command _Line History");
		this.chkBashHist.DrawIndicator = true;
		this.chkBashHist.UseUnderline = true;
		this.vbox7.Add (this.chkBashHist);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.chkBashHist]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		w5.Add (this.vbox7);
		this.GtkScrolledWindow1.Add (w5);
		this.vbox6.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow1]));
		w12.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.lblDelMethodInst = new global::Gtk.Label ();
		this.lblDelMethodInst.Name = "lblDelMethodInst";
		this.lblDelMethodInst.LabelProp = global::Mono.Unix.Catalog.GetString ("Select <b>deletion method</b>:");
		this.lblDelMethodInst.UseMarkup = true;
		this.lblDelMethodInst.Justify = ((global::Gtk.Justification)(2));
		this.vbox8.Add (this.lblDelMethodInst);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblDelMethodInst]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.rdoMinimalShred = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Minimal Overwrite (1-pass)"));
		this.rdoMinimalShred.CanFocus = true;
		this.rdoMinimalShred.Name = "rdoMinimalShred";
		this.rdoMinimalShred.DrawIndicator = true;
		this.rdoMinimalShred.UseUnderline = true;
		this.rdoMinimalShred.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox8.Add (this.rdoMinimalShred);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.rdoMinimalShred]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.rdoStandardShred = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Standard Overwrite (3-pass)"));
		this.rdoStandardShred.CanDefault = true;
		this.rdoStandardShred.CanFocus = true;
		this.rdoStandardShred.Name = "rdoStandardShred";
		this.rdoStandardShred.DrawIndicator = true;
		this.rdoStandardShred.UseUnderline = true;
		this.rdoStandardShred.Group = this.rdoMinimalShred.Group;
		this.vbox8.Add (this.rdoStandardShred);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.rdoStandardShred]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.rdoExtremeShred = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Extreme Overwrite (7-pass)"));
		this.rdoExtremeShred.CanFocus = true;
		this.rdoExtremeShred.Name = "rdoExtremeShred";
		this.rdoExtremeShred.DrawIndicator = true;
		this.rdoExtremeShred.UseUnderline = true;
		this.rdoExtremeShred.Group = this.rdoMinimalShred.Group;
		this.vbox8.Add (this.rdoExtremeShred);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.rdoExtremeShred]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.btnDelete = new global::Gtk.Button ();
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		// Container child btnDelete.Gtk.Container+ContainerChild
		global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w18 = new global::Gtk.HBox ();
		w18.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w19 = new global::Gtk.Image ();
		w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
		w18.Add (w19);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w21 = new global::Gtk.Label ();
		w21.LabelProp = global::Mono.Unix.Catalog.GetString ("_Delete");
		w21.UseUnderline = true;
		w18.Add (w21);
		w17.Add (w18);
		this.btnDelete.Add (w17);
		this.vbox8.Add (this.btnDelete);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.btnDelete]));
		w25.Position = 4;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox6.Add (this.vbox8);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox8]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox5.Add (this.vbox6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
		w27.Position = 1;
		this.vbox2.Add (this.vbox5);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox5]));
		w28.Position = 0;
		this.notebook1.Add (this.vbox2);
		// Notebook tab
		this.lblShred = new global::Gtk.Label ();
		this.lblShred.Name = "lblShred";
		this.lblShred.LabelProp = global::Mono.Unix.Catalog.GetString ("Secure Deletion");
		this.notebook1.SetTabLabel (this.vbox2, this.lblShred);
		this.lblShred.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.lblUpdateInst = new global::Gtk.Label ();
		this.lblUpdateInst.Name = "lblUpdateInst";
		this.lblUpdateInst.Ypad = 5;
		this.lblUpdateInst.LabelProp = global::Mono.Unix.Catalog.GetString ("Select <b>system update</b> action:");
		this.lblUpdateInst.UseMarkup = true;
		this.vbox10.Add (this.lblUpdateInst);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lblUpdateInst]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnRefreshPackageCatalog = new global::Gtk.Button ();
		this.btnRefreshPackageCatalog.CanFocus = true;
		this.btnRefreshPackageCatalog.Name = "btnRefreshPackageCatalog";
		this.btnRefreshPackageCatalog.UseUnderline = true;
		// Container child btnRefreshPackageCatalog.Gtk.Container+ContainerChild
		global::Gtk.Alignment w31 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w32 = new global::Gtk.HBox ();
		w32.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w33 = new global::Gtk.Image ();
		w33.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
		w32.Add (w33);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w35 = new global::Gtk.Label ();
		w35.LabelProp = global::Mono.Unix.Catalog.GetString ("_Refresh Package Catalog");
		w35.UseUnderline = true;
		w32.Add (w35);
		w31.Add (w32);
		this.btnRefreshPackageCatalog.Add (w31);
		this.vbox11.Add (this.btnRefreshPackageCatalog);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.btnRefreshPackageCatalog]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnInstallUpdates = new global::Gtk.Button ();
		this.btnInstallUpdates.CanFocus = true;
		this.btnInstallUpdates.Name = "btnInstallUpdates";
		this.btnInstallUpdates.UseUnderline = true;
		// Container child btnInstallUpdates.Gtk.Container+ContainerChild
		global::Gtk.Alignment w40 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w41 = new global::Gtk.HBox ();
		w41.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w42 = new global::Gtk.Image ();
		w42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		w41.Add (w42);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w44 = new global::Gtk.Label ();
		w44.LabelProp = global::Mono.Unix.Catalog.GetString ("_Update System");
		w44.UseUnderline = true;
		w41.Add (w44);
		w40.Add (w41);
		this.btnInstallUpdates.Add (w40);
		this.vbox11.Add (this.btnInstallUpdates);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.btnInstallUpdates]));
		w48.Position = 1;
		w48.Expand = false;
		w48.Fill = false;
		this.vbox10.Add (this.vbox11);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vbox11]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		this.hbox2.Add (this.vbox10);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox10]));
		w50.Position = 0;
		w50.Fill = false;
		this.notebook1.Add (this.hbox2);
		global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox2]));
		w51.Position = 1;
		w51.TabExpand = true;
		// Notebook tab
		this.lblSystemUpdate = new global::Gtk.Label ();
		this.lblSystemUpdate.Name = "lblSystemUpdate";
		this.lblSystemUpdate.LabelProp = global::Mono.Unix.Catalog.GetString ("System Update");
		this.notebook1.SetTabLabel (this.hbox2, this.lblSystemUpdate);
		this.lblSystemUpdate.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblFirewallInst = new global::Gtk.Label ();
		this.lblFirewallInst.Name = "lblFirewallInst";
		this.lblFirewallInst.Ypad = 5;
		this.lblFirewallInst.LabelProp = global::Mono.Unix.Catalog.GetString ("Manage <b>UFW</b> firewall:");
		this.lblFirewallInst.UseMarkup = true;
		this.lblFirewallInst.Wrap = true;
		this.lblFirewallInst.Justify = ((global::Gtk.Justification)(2));
		this.vbox3.Add (this.lblFirewallInst);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblFirewallInst]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnActivateFirewall = new global::Gtk.Button ();
		this.btnActivateFirewall.CanFocus = true;
		this.btnActivateFirewall.Name = "btnActivateFirewall";
		this.btnActivateFirewall.UseUnderline = true;
		// Container child btnActivateFirewall.Gtk.Container+ContainerChild
		global::Gtk.Alignment w53 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w54 = new global::Gtk.HBox ();
		w54.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w55 = new global::Gtk.Image ();
		w55.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
		w54.Add (w55);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w57 = new global::Gtk.Label ();
		w57.LabelProp = global::Mono.Unix.Catalog.GetString ("_Activate Firewall");
		w57.UseUnderline = true;
		w54.Add (w57);
		w53.Add (w54);
		this.btnActivateFirewall.Add (w53);
		this.vbox3.Add (this.btnActivateFirewall);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnActivateFirewall]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnDeavtivateFirewall = new global::Gtk.Button ();
		this.btnDeavtivateFirewall.CanFocus = true;
		this.btnDeavtivateFirewall.Name = "btnDeavtivateFirewall";
		this.btnDeavtivateFirewall.UseUnderline = true;
		// Container child btnDeavtivateFirewall.Gtk.Container+ContainerChild
		global::Gtk.Alignment w62 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w63 = new global::Gtk.HBox ();
		w63.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w64 = new global::Gtk.Image ();
		w64.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
		w63.Add (w64);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w66 = new global::Gtk.Label ();
		w66.LabelProp = global::Mono.Unix.Catalog.GetString ("_Deactivate Firewall");
		w66.UseUnderline = true;
		w63.Add (w66);
		w62.Add (w63);
		this.btnDeavtivateFirewall.Add (w62);
		this.vbox3.Add (this.btnDeavtivateFirewall);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnDeavtivateFirewall]));
		w70.Position = 2;
		w70.Expand = false;
		w70.Fill = false;
		this.hbox4.Add (this.vbox3);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
		w71.Position = 0;
		w71.Fill = false;
		this.notebook1.Add (this.hbox4);
		global::Gtk.Notebook.NotebookChild w72 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox4]));
		w72.Position = 2;
		// Notebook tab
		this.lblFirewall = new global::Gtk.Label ();
		this.lblFirewall.Name = "lblFirewall";
		this.lblFirewall.LabelProp = global::Mono.Unix.Catalog.GetString ("Firewall");
		this.notebook1.SetTabLabel (this.hbox4, this.lblFirewall);
		this.lblFirewall.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.lblAvInst = new global::Gtk.Label ();
		this.lblAvInst.Name = "lblAvInst";
		this.lblAvInst.Ypad = 5;
		this.lblAvInst.LabelProp = global::Mono.Unix.Catalog.GetString ("Select <b>ClamAV</b> scan type:");
		this.lblAvInst.UseMarkup = true;
		this.lblAvInst.Wrap = true;
		this.lblAvInst.Justify = ((global::Gtk.Justification)(2));
		this.vbox9.Add (this.lblAvInst);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblAvInst]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.rdoClamavHomeFolder = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Home Folder"));
		this.rdoClamavHomeFolder.CanFocus = true;
		this.rdoClamavHomeFolder.Name = "rdoClamavHomeFolder";
		this.rdoClamavHomeFolder.DrawIndicator = true;
		this.rdoClamavHomeFolder.UseUnderline = true;
		this.rdoClamavHomeFolder.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox9.Add (this.rdoClamavHomeFolder);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.rdoClamavHomeFolder]));
		w74.Position = 1;
		w74.Expand = false;
		w74.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.rdoClamavExternal = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("External Disks"));
		this.rdoClamavExternal.CanFocus = true;
		this.rdoClamavExternal.Name = "rdoClamavExternal";
		this.rdoClamavExternal.DrawIndicator = true;
		this.rdoClamavExternal.UseUnderline = true;
		this.rdoClamavExternal.Group = this.rdoClamavHomeFolder.Group;
		this.vbox9.Add (this.rdoClamavExternal);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.rdoClamavExternal]));
		w75.Position = 2;
		w75.Expand = false;
		w75.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.rdoClamavFull = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Full Computer"));
		this.rdoClamavFull.CanFocus = true;
		this.rdoClamavFull.Name = "rdoClamavFull";
		this.rdoClamavFull.DrawIndicator = true;
		this.rdoClamavFull.UseUnderline = true;
		this.rdoClamavFull.Group = this.rdoClamavHomeFolder.Group;
		this.vbox9.Add (this.rdoClamavFull);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.rdoClamavFull]));
		w76.Position = 3;
		w76.Expand = false;
		w76.Fill = false;
		this.vbox4.Add (this.vbox9);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox9]));
		w77.Position = 0;
		w77.Expand = false;
		w77.Fill = false;
		w77.Padding = ((uint)(5));
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnVirusScan = new global::Gtk.Button ();
		this.btnVirusScan.CanFocus = true;
		this.btnVirusScan.Name = "btnVirusScan";
		this.btnVirusScan.UseUnderline = true;
		// Container child btnVirusScan.Gtk.Container+ContainerChild
		global::Gtk.Alignment w78 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w79 = new global::Gtk.HBox ();
		w79.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w80 = new global::Gtk.Image ();
		w80.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_search", global::Gtk.IconSize.Menu);
		w79.Add (w80);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w82 = new global::Gtk.Label ();
		w82.LabelProp = global::Mono.Unix.Catalog.GetString ("_Scan");
		w82.UseUnderline = true;
		w79.Add (w82);
		w78.Add (w79);
		this.btnVirusScan.Add (w78);
		this.vbox4.Add (this.btnVirusScan);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnVirusScan]));
		w86.Position = 1;
		w86.Expand = false;
		w86.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnFreshclam = new global::Gtk.Button ();
		this.btnFreshclam.CanFocus = true;
		this.btnFreshclam.Name = "btnFreshclam";
		this.btnFreshclam.UseUnderline = true;
		// Container child btnFreshclam.Gtk.Container+ContainerChild
		global::Gtk.Alignment w87 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w88 = new global::Gtk.HBox ();
		w88.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w89 = new global::Gtk.Image ();
		w89.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
		w88.Add (w89);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w91 = new global::Gtk.Label ();
		w91.LabelProp = global::Mono.Unix.Catalog.GetString ("_Update Virus Database");
		w91.UseUnderline = true;
		w88.Add (w91);
		w87.Add (w88);
		this.btnFreshclam.Add (w87);
		this.vbox4.Add (this.btnFreshclam);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnFreshclam]));
		w95.Position = 2;
		w95.Expand = false;
		w95.Fill = false;
		this.hbox5.Add (this.vbox4);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox4]));
		w96.Position = 0;
		w96.Fill = false;
		this.notebook1.Add (this.hbox5);
		global::Gtk.Notebook.NotebookChild w97 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox5]));
		w97.Position = 3;
		// Notebook tab
		this.lblAntivirus = new global::Gtk.Label ();
		this.lblAntivirus.Name = "lblAntivirus";
		this.lblAntivirus.LabelProp = global::Mono.Unix.Catalog.GetString ("Antivirus");
		this.notebook1.SetTabLabel (this.hbox5, this.lblAntivirus);
		this.lblAntivirus.ShowAll ();
		this.hbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.notebook1]));
		w98.Position = 0;
		w98.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fraOutput = new global::Gtk.Frame ();
		this.fraOutput.Name = "fraOutput";
		this.fraOutput.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child fraOutput.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtOutput = new global::Gtk.TextView ();
		this.txtOutput.CanFocus = true;
		this.txtOutput.Name = "txtOutput";
		this.txtOutput.Editable = false;
		this.txtOutput.CursorVisible = false;
		this.txtOutput.Overwrite = true;
		this.txtOutput.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add (this.txtOutput);
		this.fraOutput.Add (this.GtkScrolledWindow);
		this.lblOutput = new global::Gtk.Label ();
		this.lblOutput.Name = "lblOutput";
		this.lblOutput.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output Console</b>");
		this.lblOutput.UseMarkup = true;
		this.fraOutput.LabelWidget = this.lblOutput;
		this.hbox1.Add (this.fraOutput);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fraOutput]));
		w101.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w102.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.hbox3.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hseparator4]));
		w103.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnClear = new global::Gtk.Button ();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		// Container child btnClear.Gtk.Container+ContainerChild
		global::Gtk.Alignment w104 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w105 = new global::Gtk.HBox ();
		w105.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w106 = new global::Gtk.Image ();
		w106.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
		w105.Add (w106);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w108 = new global::Gtk.Label ();
		w108.LabelProp = global::Mono.Unix.Catalog.GetString ("_Clear Console");
		w108.UseUnderline = true;
		w105.Add (w108);
		w104.Add (w105);
		this.btnClear.Add (w104);
		this.hbox3.Add (this.btnClear);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnClear]));
		w112.Position = 1;
		w112.Expand = false;
		w112.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w113.Position = 3;
		w113.Expand = false;
		w113.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.rdoStandardShred.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.about_Activated);
		this.btnDelete.Clicked += new global::System.EventHandler (this.btnDelete_Click);
		this.btnRefreshPackageCatalog.Clicked += new global::System.EventHandler (this.btnRefreshPackageCatalog_Click);
		this.btnInstallUpdates.Clicked += new global::System.EventHandler (this.btnInstallUpdates_Click);
		this.btnActivateFirewall.Clicked += new global::System.EventHandler (this.btnActivateFirewall_Click);
		this.btnDeavtivateFirewall.Clicked += new global::System.EventHandler (this.btnDeavtivateFirewall_Click);
		this.btnVirusScan.Clicked += new global::System.EventHandler (this.btnVirusScan_Click);
		this.btnFreshclam.Clicked += new global::System.EventHandler (this.btnFreshclam_Click);
		this.btnClear.Clicked += new global::System.EventHandler (this.btnClear_Click);
	}
}
